#!/bin/bash

## makeblastdb establish BLAST dataset
makeblastdb -in differentiated_genes.fa -dbtype prot -out blastdb

## blastp extract similar sequence
blastp -num_threads 12 -db blastdb -query protein.fa -outfmt 7 -seg yes -evalue 1e-5 > blast_output.txt

## convert blast output into MCL (ABC) formart
 grep -v "#"  blast_output.txt | cut -f 1,2,11 > blast_output.abc

## create .mci and .tab files for MCL cluster
mcxload -abc blast_output.abc --stream-mirror --stream-neg-log10 -stream-tf 'ceil(200)' -o blast_output.mci -write-tab blast_output.tab


## MCL clustering
mcl new/blast_output.mci -I 3

## convert gene index to gene ID
mcxdump -icl out.blast_output.mci.I30 -tabr blast_output.tab -o dump.blast_output.mci.I30


